"use client";
import Link from "next/link";import{useRef,useState}from"react";import{useSiteLanguage}from"../components/useSiteLanguage";
type Exp={role:string;company:string;years:string;details:string};
const empty=():Exp=>({role:"",company:"",years:"",details:""});
export default function Candidate(){ const en=useSiteLanguage()==="en";
 const fileRef=useRef<HTMLInputElement>(null);const[mode,setMode]=useState("home");const[file,setFile]=useState("");const[exps,setExps]=useState<Exp[]>([empty()]);const[e,setE]=useState(0);const[s,setS]=useState(0);const[phase,setPhase]=useState("experience");const[extra,setExtra]=useState({education:"",training:"",skills:"",languages:""});
 const qs=en?[["role","What was your role?","For example: Sales Associate"],["company","Where did you work?","Company or business name"],["years","When and for how long?","For example: 2025–2026, one year"],["details","What did you do in this role?","Responsibilities, goals, management, training..."]]:[["role","מה היה התפקיד?","לדוגמה: מוכרת בגדים"],["company","איפה עבדת?","שם החברה או סוג העסק"],["years","באילו שנים וכמה זמן?","לדוגמה: 2025–2026, כשנה"],["details","ספרי לי מה עשית בתפקיד","אחריות, משימות, יעדים, ניהול, הדרכות..."]];
 const upd=(k:string,v:string)=>{const a=[...exps];a[e]={...a[e],[k]:v};setExps(a)};
 if(mode==="builder"){
  if(phase==="experience"){if(s<4){const[k,q,p]=qs[s];const v=(exps[e]as any)[k];return <Wrap><span className="eyebrow">{en?"Experience":"ניסיון"} {e+1} · {en?"Step":"שלב"} {s+1}/4</span><h1>{q}</h1><input value={v} onChange={x=>upd(k,x.target.value)} placeholder={p} style={field}/><p style={{color:"#64748b"}}>{s===3?(en?"Write what you remember. AI follow-up questions will be suggested later without inventing details.":"כתבי מה שאת זוכרת. בהמשך ה-AI יוכל להציע שאלות המשך לפי סוג התפקיד, בלי להמציא פרטים."):""}</p><button disabled={!v.trim()} className="button" onClick={()=>setS(s+1)}>{en?"Continue":"המשך"}</button></Wrap>}
   return <Wrap><span className="eyebrow">{en?"Work experience":"ניסיון תעסוקתי"}</span><h1>{en?"Do you have more work experience?":"יש לך ניסיון נוסף?"}</h1><div className="choice"><b>{exps[e].role}</b><p>{exps[e].company} · {exps[e].years}</p></div><div style={{display:"flex",gap:12}}><button className="button" onClick={()=>{setExps([...exps,empty()]);setE(e+1);setS(0)}}>{en?"Yes, add another role":"כן, להוסיף תפקיד נוסף"}</button><button onClick={()=>setPhase("education")} style={secondary}>{en?"No, that’s all":"לא, סיימתי ניסיון תעסוקתי"}</button></div></Wrap>}
  const phases:any=en?{education:["Education","What did you study and where?","School, degree, professional studies...","training"],training:["Training & certificates","Any courses or certificates to add?","You can write none","skills"],skills:["Skills","Which professional skills do you have?","Service, sales, team management, Office...","languages"],languages:["Languages","Which languages do you speak and at what level?","English fluent, Hebrew native...","summary"]}:{education:["השכלה","מה למדת ואיפה?","תיכון, תואר, לימודים מקצועיים...","training"],training:["הכשרות ותעודות","יש קורסים, הכשרות או תעודות שחשוב להוסיף?","אפשר לכתוב 'אין'","skills"],skills:["כישורים","אילו כישורים מקצועיים יש לך?","שירות, מכירות, ניהול צוות, Office...","languages"],languages:["שפות","אילו שפות את יודעת ובאיזו רמה?","עברית שפת אם, אנגלית טובה...","summary"]};
  if(phase!=="summary"){const[q1,q2,p,next]=phases[phase];const v=(extra as any)[phase];return <Wrap><span className="eyebrow">{en?"CV Builder":"בניית קורות חיים"}</span><h1>{q1}</h1><p>{q2}</p><input value={v} onChange={x=>setExtra({...extra,[phase]:x.target.value})} placeholder={p} style={field}/><button disabled={!v.trim()} className="button" onClick={()=>setPhase(next)}>{en?"Continue":"המשך"}</button></Wrap>}
  return <Wrap><span className="eyebrow">{en?"Your CV draft":"טיוטת קורות החיים שלך"}</span><h1>{en?"Your work experience":"הניסיון המקצועי שלך"}</h1>{exps.map((x,i)=><div className="choice" key={i}><h2>{x.role}</h2><p><b>{x.company}</b> · {x.years}</p><p>{x.details}</p></div>)}<h2>{en?"Education":"השכלה"}</h2><p>{extra.education}</p><h2>{en?"Training":"הכשרות"}</h2><p>{extra.training}</p><h2>{en?"Skills":"כישורים"}</h2><p>{extra.skills}</p><h2>{en?"Languages":"שפות"}</h2><p>{extra.languages}</p><div style={{display:"flex",gap:12}}><button onClick={()=>{setPhase("experience");setE(0);setS(0)}} style={secondary}>{en?"Edit":"עריכה"}</button><Link className="button" href="/candidate/jobs">{en?"Approve and continue to jobs":"אישור והמשך למשרות ←"}</Link></div></Wrap>
 }
 if(mode==="paste")return <Wrap><h1>{en?"Paste your CV":"הדבקת קורות חיים"}</h1><textarea style={{width:"100%",minHeight:240}}/><Link className="button" href="/candidate/review">{en?"Continue to analysis":"המשך לניתוח"}</Link></Wrap>;
 return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={card}><span className="eyebrow">{en?"Candidate":"מסלול מועמד/ת"}</span><h1>{en?"Let’s start with your CV":"בואו נתחיל מקורות החיים שלך"}</h1><input ref={fileRef} type="file" accept=".pdf,.doc,.docx" hidden onChange={x=>setFile(x.target.files?.[0]?.name||"")}/><div className="cvEntryActions"><button type="button" onClick={()=>fileRef.current?.click()} className="button cvEntryButton">{file||(en?"Upload PDF or Word":"העלאת PDF או Word")}</button><button type="button" className="cvEntryButton cvEntrySecondary" onClick={()=>setMode("paste")}>{en?"Paste your CV":"הדבקת קורות חיים"}</button><button type="button" className="cvEntryButton cvEntrySecondary" onClick={()=>setMode("builder")}>{en?"I don’t have a CV — help me build one":"אין לי קורות חיים — עזרו לי לבנות"}</button></div>{file&&<Link className="button" href="/candidate/review" style={{marginTop:16}}>{en?"Continue to analysis":"המשך לניתוח ←"}</Link>}</section></main>
}
function Wrap({children}:{children:React.ReactNode}){return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={card}>{children}</section></main>}
const card={maxWidth:720,margin:"60px auto",background:"#fff",padding:40,borderRadius:24,border:"1px solid #e8e4dc"};const field={width:"100%",padding:14,border:"1px solid #ddd",borderRadius:12,font:"inherit",marginBottom:16};const secondary={padding:12,border:"1px solid #ddd",borderRadius:12,background:"#fff",cursor:"pointer"};
