"use client";
import Link from "next/link";
import { useRef, useState } from "react";

export default function Candidate(){
 const fileRef=useRef<HTMLInputElement>(null);
 const [mode,setMode]=useState<"home"|"paste"|"builder">("home");
 const [file,setFile]=useState("");
 if(mode==="paste") return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={{maxWidth:650,margin:"70px auto",background:"#fff",padding:40,borderRadius:24,border:"1px solid #e8e4dc"}}><button onClick={()=>setMode("home")} style={{border:0,background:"transparent",cursor:"pointer"}}>→ חזרה</button><h1>הדבקת קורות חיים</h1><p style={{color:"#64748b"}}>הדביקי כאן את תוכן קורות החיים. בשלב הבא המערכת תחלץ מהם את הפרופיל המקצועי.</p><textarea aria-label="קורות חיים" placeholder="הדביקי כאן את קורות החיים..." style={{width:"100%",minHeight:240,padding:16,border:"1px solid #ddd",borderRadius:12,font:"inherit",direction:"rtl"}}/><button className="button" style={{border:0,marginTop:16,cursor:"pointer"}}>המשך לניתוח</button></section></main>;
 if(mode==="builder") return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={{maxWidth:650,margin:"70px auto",background:"#fff",padding:40,borderRadius:24,border:"1px solid #e8e4dc"}}><button onClick={()=>setMode("home")} style={{border:0,background:"transparent",cursor:"pointer"}}>→ חזרה</button><span className="eyebrow">בניית קורות חיים</span><h1>נתחיל מהניסיון האחרון שלך</h1><p style={{color:"#64748b",lineHeight:1.7}}>אין צורך להכין הכול מראש. נשאל כמה שאלות קצרות ונבנה יחד פרופיל מקצועי.</p><input placeholder="מה היה התפקיד האחרון שלך?" style={{width:"100%",padding:14,border:"1px solid #ddd",borderRadius:12,font:"inherit"}}/><button className="button" style={{border:0,marginTop:16,cursor:"pointer"}}>המשך</button></section></main>;
 return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={{maxWidth:650,margin:"70px auto",background:"#fff",padding:40,borderRadius:24,border:"1px solid #e8e4dc"}}><span className="eyebrow">מסלול מועמד/ת</span><h1>בואו נתחיל מקורות החיים שלך</h1><p style={{color:"#64748b",lineHeight:1.7}}>הפרופיל הופך לפעיל אחרי פרטים בסיסיים וקורות חיים. את שאר המידע נשלים רק כשבאמת יהיה בו צורך.</p><input ref={fileRef} type="file" accept=".pdf,.doc,.docx" hidden onChange={e=>setFile(e.target.files?.[0]?.name||"")}/><div style={{display:"grid",gap:12,marginTop:28}}><button onClick={()=>fileRef.current?.click()} className="button" style={{border:0,cursor:"pointer",justifyContent:"center"}}>{file||"העלאת PDF או Word"}</button><button onClick={()=>setMode("paste")} style={{padding:12,borderRadius:12,border:"1px solid #ddd",background:"#fff",cursor:"pointer"}}>הדבקת קורות חיים</button><button onClick={()=>setMode("builder")} style={{padding:12,borderRadius:12,border:"1px solid #ddd",background:"#fff",cursor:"pointer"}}>אין לי קורות חיים — עזרו לי לבנות</button></div>{file&&<p style={{color:"#2f6f6a",marginTop:16}}>✓ הקובץ נבחר. בשלב הבא נחבר את ניתוח קורות החיים.</p>}</section></main>
}