"use client";
import Link from "next/link";import{useRef,useState}from"react";
type Exp={role:string;company:string;years:string;details:string};
const empty=():Exp=>({role:"",company:"",years:"",details:""});
export default function Candidate(){
 const fileRef=useRef<HTMLInputElement>(null);const[mode,setMode]=useState("home");const[file,setFile]=useState("");const[exps,setExps]=useState<Exp[]>([empty()]);const[e,setE]=useState(0);const[s,setS]=useState(0);const[phase,setPhase]=useState("experience");const[extra,setExtra]=useState({education:"",training:"",skills:"",languages:""});
 const qs=[["role","מה היה התפקיד?","לדוגמה: מוכרת בגדים"],["company","איפה עבדת?","שם החברה או סוג העסק"],["years","באילו שנים וכמה זמן?","לדוגמה: 2025–2026, כשנה"],["details","ספרי לי מה עשית בתפקיד","אחריות, משימות, יעדים, ניהול, הדרכות..."]];
 const upd=(k:string,v:string)=>{const a=[...exps];a[e]={...a[e],[k]:v};setExps(a)};
 if(mode==="builder"){
  if(phase==="experience"){if(s<4){const[k,q,p]=qs[s];const v=(exps[e]as any)[k];return <Wrap><span className="eyebrow">ניסיון {e+1} · שלב {s+1}/4</span><h1>{q}</h1><input value={v} onChange={x=>upd(k,x.target.value)} placeholder={p} style={field}/><p style={{color:"#64748b"}}>{s===3?"כתבי מה שאת זוכרת. בהמשך ה-AI יוכל להציע שאלות המשך לפי סוג התפקיד, בלי להמציא פרטים.":""}</p><button disabled={!v.trim()} className="button" onClick={()=>setS(s+1)}>המשך</button></Wrap>}
   return <Wrap><span className="eyebrow">ניסיון תעסוקתי</span><h1>יש לך ניסיון נוסף?</h1><div className="choice"><b>{exps[e].role}</b><p>{exps[e].company} · {exps[e].years}</p></div><div style={{display:"flex",gap:12}}><button className="button" onClick={()=>{setExps([...exps,empty()]);setE(e+1);setS(0)}}>כן, להוסיף תפקיד נוסף</button><button onClick={()=>setPhase("education")} style={secondary}>לא, סיימתי ניסיון תעסוקתי</button></div></Wrap>}
  const phases:any={education:["השכלה","מה למדת ואיפה?","תיכון, תואר, לימודים מקצועיים...","training"],training:["הכשרות ותעודות","יש קורסים, הכשרות או תעודות שחשוב להוסיף?","אפשר לכתוב 'אין'","skills"],skills:["כישורים","אילו כישורים מקצועיים יש לך?","שירות, מכירות, ניהול צוות, Office...","languages"],languages:["שפות","אילו שפות את יודעת ובאיזו רמה?","עברית שפת אם, אנגלית טובה...","summary"]};
  if(phase!=="summary"){const[q1,q2,p,next]=phases[phase];const v=(extra as any)[phase];return <Wrap><span className="eyebrow">בניית קורות חיים</span><h1>{q1}</h1><p>{q2}</p><input value={v} onChange={x=>setExtra({...extra,[phase]:x.target.value})} placeholder={p} style={field}/><button disabled={!v.trim()} className="button" onClick={()=>setPhase(next)}>המשך</button></Wrap>}
  return <Wrap><span className="eyebrow">טיוטת קורות החיים שלך</span><h1>הניסיון המקצועי שלך</h1>{exps.map((x,i)=><div className="choice" key={i}><h2>{x.role}</h2><p><b>{x.company}</b> · {x.years}</p><p>{x.details}</p></div>)}<h2>השכלה</h2><p>{extra.education}</p><h2>הכשרות</h2><p>{extra.training}</p><h2>כישורים</h2><p>{extra.skills}</p><h2>שפות</h2><p>{extra.languages}</p><div style={{display:"flex",gap:12}}><button onClick={()=>{setPhase("experience");setE(0);setS(0)}} style={secondary}>עריכה</button><Link className="button" href="/candidate/jobs">אישור והמשך למשרות ←</Link></div></Wrap>
 }
 if(mode==="paste")return <Wrap><h1>הדבקת קורות חיים</h1><textarea style={{width:"100%",minHeight:240}}/><Link className="button" href="/candidate/review">המשך לניתוח</Link></Wrap>;
 return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={card}><span className="eyebrow">מסלול מועמד/ת</span><h1>בואו נתחיל מקורות החיים שלך</h1><input ref={fileRef} type="file" accept=".pdf,.doc,.docx" hidden onChange={x=>setFile(x.target.files?.[0]?.name||"")}/><div style={{display:"grid",gap:12}}><button onClick={()=>fileRef.current?.click()} className="button">{file||"העלאת PDF או Word"}</button><button onClick={()=>setMode("paste")}>הדבקת קורות חיים</button><button onClick={()=>setMode("builder")}>אין לי קורות חיים — עזרו לי לבנות</button></div>{file&&<Link className="button" href="/candidate/review" style={{marginTop:16}}>המשך לניתוח ←</Link>}</section></main>
}
function Wrap({children}:{children:React.ReactNode}){return <main className="shell"><nav className="nav"><Link className="brand" href="/">Recruitment AI</Link></nav><section style={card}>{children}</section></main>}
const card={maxWidth:720,margin:"60px auto",background:"#fff",padding:40,borderRadius:24,border:"1px solid #e8e4dc"};const field={width:"100%",padding:14,border:"1px solid #ddd",borderRadius:12,font:"inherit",marginBottom:16};const secondary={padding:12,border:"1px solid #ddd",borderRadius:12,background:"#fff",cursor:"pointer"};
